# Generated by Django 4.2.7 on 2025-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='There could be your description', max_length=150),
        ),
    ]
