version: '3.9'

services:
  dm_db:
    image: postgres:17
    container_name: dm_db
    restart: always
    environment:
      POSTGRES_PASSWORD: h1h12h13
    volumes:
      - ~/.pg/pg_data/dm:/var/lib/postgresql/data/
    env_file:
      - .env

  db_web:
    build: .
    command: python /usr/src/dm_rest/manage.py runserver 0.0.0.0:8000
    container_name: dm_django
    volumes:
      - .:/usr/src/dm_rest
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - dm_db


volumes:
  postgres_data: