# Generated by Django 4.0.1 on 2024-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='genres',
            field=models.ManyToManyField(blank=True, to='chat.Genre'),
        ),
    ]
