# Generated by Django 4.2.7 on 2025-01-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TextField(),
        ),
    ]
