# Generated by Django 4.0.1 on 2025-02-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='imagemsg',
            field=models.ImageField(blank=True, upload_to='message/%Y/%m/%d/'),
        ),
    ]
