# Generated by Django 4.0.1 on 2025-02-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_imagemsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='imagemsg',
        ),
        migrations.AddField(
            model_name='message',
            name='image_msg',
            field=models.ImageField(blank=True, upload_to='images/message_pictures'),
        ),
    ]
