# Generated by Django 4.0.1 on 2025-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_messagedata_remove_message_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_data',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='MessageData',
        ),
    ]
