# Generated by Django 4.0.1 on 2025-04-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_remove_message_image_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='usefullness',
            field=models.BooleanField(default=False),
        ),
    ]
