# Generated by Django 4.0.1 on 2025-04-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_message_usefullness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='usefullness',
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
