# Generated by Django 4.0.1 on 2025-02-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('children', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tree.root')),
            ],
        ),
    ]
