# Generated by Django 4.0.1 on 2025-02-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_root_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='root',
            old_name='children',
            new_name='parent',
        ),
    ]
