# Generated by Django 4.0.1 on 2025-02-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_rename_children_root_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Root',
        ),
    ]
